# Generated by Django 5.2 on 2025-04-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shipping_address',
            new_name='shipping_address',
        ),
    ]
